# Generated by Django 4.2.13 on 2024-06-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
