# Generated by Django 4.2.13 on 2024-06-12 05:45

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[accounts.validators.validate_mobile]),
        ),
    ]
